[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Disable Edge Functions to prevent Deno requirement
[edge_functions]
  # No edge functions defined - this prevents Netlify from trying to set up the Edge Functions environment

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200