[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5174
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"